# Generated by Django 4.0.2 on 2023-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_tradingprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingprofit',
            name='percentage',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=15),
            preserve_default=False,
        ),
    ]
