# Generated by Django 4.0.2 on 2023-02-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0004_tradingprofit_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
