# Generated by Django 4.0.2 on 2023-02-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0008_percentageprovider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentageprovider',
            name='percent',
            field=models.DecimalField(decimal_places=5, default=False, max_digits=15),
            preserve_default=False,
        ),
    ]
