# Generated by Django 4.0.2 on 2023-02-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0010_newinvestment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewInvestment',
        ),
        migrations.DeleteModel(
            name='PercentageProvider',
        ),
    ]
