# Generated by Django 4.0.2 on 2023-03-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0011_delete_newinvestment_delete_percentageprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
