# Generated by Django 4.0.2 on 2023-03-06 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposit', '0014_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI Payment', 'UPI Payment'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Bitcoin', 'Bitcoin'), ('USDT', 'USDT'), ('Ethereum', 'Ethereum'), ('BUSD', 'BUSD'), ('Dogecoin', 'Dogecoin'), ('BNB', 'BNB'), ('Litecoin', 'Litecoin'), ('USDC', 'USDC'), ('SOL Solana', 'SOL Solana'), ('BNB', 'BNB'), ('MATIC Polygon', 'MATIC Polygon'), ('XRP Ripple', 'XRP Ripple'), ('ADA Cardano', 'ADA Cardano')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt4_5', models.CharField(blank=True, max_length=450, null=True)),
                ('password', models.CharField(blank=True, max_length=450, null=True)),
                ('server', models.CharField(blank=True, max_length=450, null=True)),
                ('status', models.BooleanField(default=True)),
                ('action', models.CharField(blank=True, max_length=450, null=True)),
                ('active', models.BooleanField(default=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
