# Generated by Django 4.0.2 on 2023-02-15 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Balance')),
                ('roi_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('total_roi_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('level_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('total_level_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('direct_refer_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('total_direct_refer_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('bot_profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('trading_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('code', models.CharField(blank=True, max_length=12)),
                ('account_address', models.CharField(blank=True, max_length=60, null=True)),
                ('active', models.BooleanField(default=True)),
                ('invested', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downlines', to='mainapp.customer', verbose_name='Up Line')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'unique_together': {('parent', 'account')},
            },
        ),
    ]
