# Generated by Django 4.0.2 on 2023-02-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bot_profit',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='direct_refer_income',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='level_income',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='roi_profit',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_direct_refer_income',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_level_income',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_roi_profit',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='trading_balance',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True),
        ),
    ]
