# Generated by Django 4.0.2 on 2023-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_customer_balance_alter_customer_bot_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='today_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
