# Generated by Django 4.0.2 on 2023-02-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_customer_today_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='today_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
