# Generated by Django 4.0.2 on 2023-02-22 05:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WithdrawalInfo',
            new_name='WithdrawalInfos',
        ),
    ]
