# Generated by Django 4.0.2 on 2023-02-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0005_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='withdraw_amount',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
