# Generated by Django 4.0.2 on 2023-02-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprofithistory',
            name='today_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyprofithistory',
            name='monthly_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearlyprofithistory',
            name='yearly_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
