# Generated by Django 4.0.2 on 2023-02-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_profiteprovidedaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprofithistory',
            name='today_percent',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyprofithistory',
            name='monthly_percent',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='profiteprovidedaily',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='yearlyprofithistory',
            name='yearly_percent',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
