# Generated by Django 4.0.2 on 2023-02-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_percentprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PercentProvider',
        ),
        migrations.DeleteModel(
            name='ProfiteProvideDaily',
        ),
    ]
